--CRIACAO DE TABELAS
    
CREATE TABLE SISTEMA(
N_DO_SISTEMA NUMBER(12, 0) PRIMARY KEY,
COORDENADAS VARCHAR(6)   
);

CREATE TABLE PLANETA(
N_DO_SISTEMA NUMBER(12, 0),
	POSICAO NUMBER(4),
	NOME_PLANETA VARCHAR(40),
    
CONSTRAINT PLANETA_FK FOREIGN KEY (N_DO_SISTEMA) REFERENCES SISTEMA ON DELETE CASCADE, 
CONSTRAINT PLANETA_PK PRIMARY KEY (N_DO_SISTEMA, POSICAO) 
);

CREATE TABLE ESPACO_PORTO(
	CODIGO NUMBER(18, 0) PRIMARY KEY, 
	N_DO_SISTEMA NUMBER(12, 0) NOT NULL,
	POSICAO NUMBER(4) NOT NULL,
DESCRICAO VARCHAR(200),
CONSTRAINT EP_FK FOREIGN KEY (N_DO_SISTEMA, POSICAO) REFERENCES PLANETA ON DELETE CASCADE,
CONSTRAINT EP_U UNIQUE (N_DO_SISTEMA, POSICAO)
);

CREATE TABLE DEPARTAMENTO(
	CODIGO NUMBER(18, 0),
    	COD	NUMBER(4),
    	SUP_CODIGO NUMBER(18, 0),
    	SUP_COD NUMBER(4, 0),
    	CONSTRAINT EPD_PK FOREIGN KEY(CODIGO) REFERENCES ESPACO_PORTO ON DELETE CASCADE,
    	CONSTRAINT DEP_PK PRIMARY KEY(CODIGO, COD),
    	CONSTRAINT DEP_FK FOREIGN KEY (SUP_CODIGO, SUP_COD) REFERENCES Departamento ON DELETE CASCADE 
);
CREATE TABLE FUNCOES(

	FUNC VARCHAR(100) PRIMARY KEY,
	DESCRICAO VARCHAR(200)
);

CREATE TABLE FUNCIONARIO(
	ID_GALACTICO NUMBER(12, 0) PRIMARY KEY,
    	ZONA NUMBER(8, 0),
    	BLOCO NUMBER(6, 0),
    	NUM NUMBER(5, 0)
);

CREATE TABLE CONTATO(
	ID_GALACTICO NUMBER(12, 0), 
    	CONTATO VARCHAR(40),
    	CONSTRAINT CONT_FK FOREIGN KEY(ID_GALACTICO) REFERENCES FUNCIONARIO ON DELETE CASCADE,
   	 CONSTRAINT CONT_PK PRIMARY KEY(ID_GALACTICO, CONTATO)
);

CREATE TABLE GRATIFICACAO(
	NUM NUMBER(6,0) PRIMARY KEY,
  	VALOR NUMBER(5, 2)
);

CREATE TABLE EMPREGA(
CODIGO NUMBER(18, 0),
    	COD	NUMBER(4,0),
    	ID_GALACTICO NUMBER(12, 0),
    	FUNC VARCHAR(100),
    	DATA_ VARCHAR(12),
    	CONSTRAINT EMDEP_FK FOREIGN KEY (CODIGO, COD) REFERENCES DEPARTAMENTO ON DELETE CASCADE,
    	CONSTRAINT EMF_FK FOREIGN KEY(ID_GALACTICO) REFERENCES FUNCIONARIO ON DELETE CASCADE,
    	CONSTRAINT EMFUN_FK FOREIGN KEY(FUNC) REFERENCES FUNCOES ON DELETE CASCADE,
    	CONSTRAINT EMP_FK PRIMARY KEY(CODIGO, COD, ID_GALACTICO, FUNC, DATA_)
);

CREATE TABLE BONUS(
    	NUM NUMBER(6,0),
    	CODIGO NUMBER(18, 0),
    	COD NUMBER(4, 0),
    	ID_GALACTICO NUMBER(12, 0),
    	FUNC VARCHAR(100),
    	DATA_ VARCHAR(12),
    	CONSTRAINT BONUS_FK PRIMARY KEY(NUM, CODIGO, COD, ID_GALACTICO, FUNC, DATA_)
);

CREATE TABLE NAVE(
	PLACA VARCHAR(14) PRIMARY KEY, 
    	TIPO VARCHAR(20), 
    	MASSA_MAX NUMBER(8), 
    	RE NUMBER(16,0), 
    	ID_GALACTICO NUMBER(12, 0),
    	CATEGORIA NUMBER(1)
);

CREATE TABLE PASSAGEIRO(
    	ID_GALACTICO NUMBER(12,0) PRIMARY KEY
);

CREATE TABLE PILOTO(
CGH NUMBER(8,0) PRIMARY KEY
);

CREATE TABLE MOVIMENTACAO(
    	N_VOO NUMBER(20,0) PRIMARY KEY,
    	TIPO_MOV VARCHAR(40),
    	CGH NUMBER(18, 0),
    	CODIGO NUMBER(18, 0),
    	SAIDA_OU_CHEGADA VARCHAR(12),
    	TIMESTAMP_ VARCHAR(19),
    	PLACA VARCHAR(14),
    	CONSTRAINT MOVPI_FK FOREIGN KEY (CGH) REFERENCES PILOTO ON DELETE CASCADE,
    	CONSTRAINT MOVEP_FK FOREIGN KEY (CODIGO) REFERENCES ESPACO_PORTO ON DELETE CASCADE,
    	CONSTRAINT MOVNAVE_FK FOREIGN KEY (PLACA) REFERENCES NAVE ON DELETE CASCADE
);

CREATE TABLE CARREGA(
    	N_VOO NUMBER(20, 0),
    	ID_GALACTICO NUMBER(12,0),
    	CONSTRAINT CARREGA_PK PRIMARY KEY (N_VOO, ID_GALACTICO)
);
